# Generated by Django 2.1.5 on 2019-02-08 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(default=1, help_text='How many years of experience')),
                ('salary', models.FloatField(default=0)),
                ('expertise', models.PositiveSmallIntegerField(choices=[(1, 'C'), (2, 'C++'), (3, 'Java'), (4, 'Python')], default=4)),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'teacher'), (2, 'student')], default=1)),
                ('address', models.TextField(help_text='Enter current address', max_length=200)),
                ('contact_no', models.IntegerField(default=0, help_text='Enter mobile number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.PositiveSmallIntegerField(choices=[(1, 'Red'), (2, 'Green'), (3, 'Yellow'), (4, 'Blue')], default=1)),
                ('enrolement_date', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.Profile'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='faculty',
            field=models.ManyToManyField(to='school.Faculty'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student'),
        ),
    ]
